apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      volumes: 
        - name: shared-log
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: log-writer
          image: ruhulaminjr/log_writer:latest
          env:
            - name: LOG_DIRECTORY
              value: "/usr/src/app/files" 
          volumeMounts: 
            - name: shared-log          
              mountPath: /usr/src/app/files

        - name: log-response
          image: ruhulaminjr/log_response:latest
          env:
            - name: LOG_DIRECTORY
              value: "/usr/src/app/files" 
          volumeMounts: 
            - name: shared-log
              mountPath: /usr/src/app/files
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-default-agent-0